/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankappdemo.guies;

import bankappdemo.business.concretes.CustomerManager;
import bankappdemo.entities.Customer;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class LoginGUI extends javax.swing.JFrame {

    private CustomerManager customerManager = new CustomerManager();

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        tbxIdentity = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        tbxPassword = new javax.swing.JPasswordField();
        lblErrorIdentity = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        cbxPassword = new javax.swing.JCheckBox();
        jButtonForgetPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setText("REGİSTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Identity: ");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Password :");

        tbxIdentity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbxIdentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxIdentityActionPerformed(evt);
            }
        });
        tbxIdentity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxIdentityKeyReleased(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        tbxPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbxPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxPasswordKeyReleased(evt);
            }
        });

        lblErrorIdentity.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblErrorIdentity.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorPassword.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblErrorPassword.setForeground(new java.awt.Color(255, 0, 0));

        cbxPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxPassword.setText("Show Password");
        cbxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPasswordActionPerformed(evt);
            }
        });

        jButtonForgetPassword.setText("Forget");
        jButtonForgetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForgetPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(jButtonForgetPassword)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(lblErrorIdentity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLogin)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName)
                                    .addComponent(lblPassword))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                                                .addComponent(cbxPassword))
                                            .addComponent(lblErrorPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tbxPassword)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbxIdentity)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister)
                            .addGap(125, 125, 125)))
                    .addGap(4, 4, 4)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(jButtonForgetPassword)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblName)
                        .addComponent(tbxIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblErrorIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPassword)
                        .addComponent(tbxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblErrorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxPassword)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addComponent(btnLogin)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnRegister)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tbxIdentity.setText(null);
        tbxPassword.setText(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        RegisterGUI registerGUI = new RegisterGUI();
        registerGUI.show();
        dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void tbxIdentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxIdentityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxIdentityActionPerformed

    private void tbxIdentityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxIdentityKeyReleased
        lblErrorIdentity.setText("");
    }//GEN-LAST:event_tbxIdentityKeyReleased

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        lblErrorIdentity.setText(null);
        lblErrorPassword.setText(null);

        if ((tbxIdentity.getText().equals("")) && (tbxPassword.getText().equals(""))) {
            lblErrorIdentity.setText("* Write Identity");
            lblErrorPassword.setText("* Write Password");
        } else if ((tbxIdentity.getText().equals(""))) {
            lblErrorIdentity.setText("* Write Identity");
        } else if ((tbxPassword.getText().equals(""))) {
            lblErrorPassword.setText("* Write Password");
        } else {
            if (customerManager.checkLogin(tbxIdentity.getText(), tbxPassword.getText())) {
                JOptionPane.showMessageDialog(null, "Login Successful");
                Customer customer = customerManager.getByIdentityCustomer(tbxIdentity.getText());
                if (customer.getId() == 1) {
                    AdminHomeGUI adminHomeGUI = new AdminHomeGUI();
                    adminHomeGUI.show();
                    dispose();
                } else {

                    HomeGUI homeGUI = new HomeGUI(customer.getName(), customer.getId());
                    homeGUI.show();
                    dispose();

                }
            } else {
                JOptionPane.showMessageDialog(null, "Password is Wrong");
            }

            /*if (resultSet.getString("Identity").equals(tbxIdentity.getText())) {
                        System.out.println("Success");
                        check = 1;
                        if (resultSet.getString("Password").equals(tbxPassword.getText())) {
                            JOptionPane.showMessageDialog(null, "Login Successful");
                            //new HomeGUI(infoName).isVisible(true);
                            if (resultSet.getInt("ID") == 1) {
                                AdminHomeGUI adminHomeGUI = new AdminHomeGUI();
                                adminHomeGUI.show();
                                dispose();
                            } else {
                                HomeGUI homeGUI = new HomeGUI(resultSet.getString("Name"), resultSet.getInt("ID"));
                                homeGUI.show();
                                dispose();
                            }
                            
                        } else {
                            //JOptionPane.showMessageDialog(null, "Password is Wrong");
                            lblErrorPassword.setText("* Password is Wrong");
                            break;
                        }
                    } else {
                        //JOptionPane.showMessageDialog(null, "Login Unsuccessful");
                        //break;
                    }
                
                if (check == 0) {
                    //JOptionPane.showMessageDialog(null, "Name is Wrong ");
                    lblErrorIdentity.setText("* Identity is Wrong");
                }*/
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void tbxPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxPasswordKeyReleased
        lblErrorPassword.setText("");
    }//GEN-LAST:event_tbxPasswordKeyReleased

    private void cbxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPasswordActionPerformed
        if (cbxPassword.isSelected()) {
            tbxPassword.setEchoChar((char) 0);
        } else {
            tbxPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbxPasswordActionPerformed

    private void jButtonForgetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForgetPasswordActionPerformed
        ForgetPasswordGUI forgetPasswordGUI = new ForgetPasswordGUI();
        forgetPasswordGUI.show();
        dispose();
    }//GEN-LAST:event_jButtonForgetPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbxPassword;
    private javax.swing.JButton jButtonForgetPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrorIdentity;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField tbxIdentity;
    private javax.swing.JPasswordField tbxPassword;
    // End of variables declaration//GEN-END:variables
}
